(cl:defpackage rft_sensor_serial-srv
  (:use )
  (:export
   "MULTIPLIER"
   "<MULTIPLIER-REQUEST>"
   "MULTIPLIER-REQUEST"
   "<MULTIPLIER-RESPONSE>"
   "MULTIPLIER-RESPONSE"
   "RFT_OPERATION"
   "<RFT_OPERATION-REQUEST>"
   "RFT_OPERATION-REQUEST"
   "<RFT_OPERATION-RESPONSE>"
   "RFT_OPERATION-RESPONSE"
  ))

