// Generated by gencpp from file rft_sensor_serial/rft_operationResponse.msg
// DO NOT EDIT!


#ifndef RFT_SENSOR_SERIAL_MESSAGE_RFT_OPERATIONRESPONSE_H
#define RFT_SENSOR_SERIAL_MESSAGE_RFT_OPERATIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rft_sensor_serial
{
template <class ContainerAllocator>
struct rft_operationResponse_
{
  typedef rft_operationResponse_<ContainerAllocator> Type;

  rft_operationResponse_()
    : result(0)  {
    }
  rft_operationResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct rft_operationResponse_

typedef ::rft_sensor_serial::rft_operationResponse_<std::allocator<void> > rft_operationResponse;

typedef boost::shared_ptr< ::rft_sensor_serial::rft_operationResponse > rft_operationResponsePtr;
typedef boost::shared_ptr< ::rft_sensor_serial::rft_operationResponse const> rft_operationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator1> & lhs, const ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator1> & lhs, const ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rft_sensor_serial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25458147911545c320c4c0a299eff763";
  }

  static const char* value(const ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25458147911545c3ULL;
  static const uint64_t static_value2 = 0x20c4c0a299eff763ULL;
};

template<class ContainerAllocator>
struct DataType< ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rft_sensor_serial/rft_operationResponse";
  }

  static const char* value(const ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 result\n"
"\n"
;
  }

  static const char* value(const ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rft_operationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rft_sensor_serial::rft_operationResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RFT_SENSOR_SERIAL_MESSAGE_RFT_OPERATIONRESPONSE_H
